startDelaySeconds: 0
lowercaseOutputName: true
lowercaseOutputLabelNames: true
rules:
  - pattern: "kafka.server<type=(.+), name=(.+)><>Value"
    name: kafka_server_$1_$2
    type: GAUGE
  - pattern: "java.lang<type=Memory><>HeapMemoryUsage"
    name: jvm_memory_heap_usage
    type: GAUGE
    attrNameSnakeCase: true