services:
  grafana:
    image: grafana/grafana:10.0.3
    container_name: grafana
    ports:
      - 3005:3000
    volumes:
      - ./grafana-datasources.yml:/etc/grafana/provisioning/datasources/datasources.yaml
      - grafana-data:/var/lib/grafana
    networks:
      - kafka-network
      
  prometheus:
    image: prom/prometheus:v2.46.0
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prom-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=5d'
      - '--storage.tsdb.retention.size=10GB'
      - '--storage.tsdb.min-block-duration=1h'
      - '--storage.tsdb.max-block-duration=12h'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    networks:
      - kafka-network

  nodeexporter:
    image: prom/node-exporter:v1.6.1
    container_name: nodeexporter
    ports:
      - 9100:9100
    networks:
      - kafka-network

volumes:
  grafana-data:
  prom-data:

networks: 
  kafka-network: 
    name: kafka-network
    driver: bridge  
    external: true 
