global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

scrape_configs:
- job_name: nodeexporter
  honor_timestamps: true
  scheme: http
  static_configs:
  - targets:
    - nodeexporter:9100
  relabel_configs:
    - source_labels: [__address__]
      regex: '.*'
      target_label: instance
      replacement: 'node'

- job_name: 'kafka-jmx'
  static_configs:
    - targets: ['kafka1:7071']  # Replace with actual broker/controller IPs if remote
  metrics_path: /metrics
  scheme: http
  relabel_configs:
    - source_labels: [__address__]
      target_label: instance